### PR TITLE
#24 explode functionality

### LINKED ISSUE #24: Explode Functionality
## Question
Do we want to add the explode functionality from [Enceladus](https://github.com/AbsaOSS/enceladus/blob/develop/utils/src/main/scala/za/co/absa/enceladus/utils/explode/ExplodeTools.scala)?

### PR DESCRIPTION
**Pull request by AdrianOlosutean**
Closes #24

### CODE REVIEW

**Review by dk1844 — DISMISSED** [review]
LGTM (just read the code).
I guess you have taken it from Enceladus as-is, right?

**Comment by AdrianOlosutean** [comment]
> LGTM (just read the code). I guess you have taken it from Enceladus as-is, right?

Yes, just adapting the tests for Spark 3.1.2

**Review by benedeki — COMMENTED** [review]
I would place `ExplodeTools` into `utils` as `ExplodeUtils`, the `Explosion` and `ExplosionContext` into `utils/explode`.
Finally `JsonUtils` move into `utils` too.

**Review by dk1844 — APPROVED** [review]
Still LGTM, but @benedeki says actually makes sense :)

> I would place `ExplodeTools` into `utils` as `ExplodeUtils`, the `Explosion` and `ExplosionContext` into `utils/explode`. Finally `JsonUtils` move into `utils` too.

**Pull request merged**
