### PR TITLE
#74 spark 3.3 added to project matrix

### LINKED ISSUE #74: Add support for Spark 3.3
## Background
Spark 3.3 build axis is missing, add it.

### PR DESCRIPTION
**Pull request by dk1844**
Adds Spark 3.3 support.

Tests passing for all combinations, I have not attempted to use the library in another project.

Fixes #74

### CODE REVIEW

**Review by jakipatryk — APPROVED** [review]
LGTM, checked code and ran build/tests. Just one thing - should this version be added to the table at the top of README in this PR?

**Review by benedeki — DISMISSED** [review]
LGTM

**Comment by dk1844** [comment]
> LGTM, checked code and ran build/tests. Just one thing - should this version be added to the table at the top of README in this PR?
@jakipatryk 

Thanks for the tip, I have added the Spark3.3 entries. The Maven central version will appear as `unknown` until releaes.

**Review by jakipatryk — APPROVED** [review]

**Review by lsulak — APPROVED** [review]
LGTM

**Pull request merged**
